### ISSUE TITLE
Add heathcheck support

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/Micronetes#10]
We should add health checking support to the host to know if a service is running properly.

**Comment by grahamehorner** [comment]
@davidfowl would/could this be supported via KEDA ?

**Comment by spboyer** [comment]
There are `livenessProbe` and `readinessProbe` supported in K8s. 

`livenessProbe` would ping on an interval reporting status, `readinessProbe` is used to check the start-up phase of a container (typically 10s after).

Are we looking to support both here?

**Comment by spboyer** [comment]
Example of configuring a `livenessProbe` for health checks, could follow the same semantics in the m8s.yaml

```
livenessProbe:
  initialDelaySeconds: 2
  periodSeconds: 5
  httpGet:
    path: /health
    port: 9876
```
