### ISSUE TITLE
Support for container networks / multicontainer workloads

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [davidfowl/Micronetes#22]
This project is a great project!

I defined a m8s file to standup a ElasticSearch and Kibana along with my csproj and noticed that there isn't support yet for linking containers or for joining them the same docker network.

I also had a little trouble scripting around that limitation because of the randomization of the container names. 

I know there can't be support for everything, but a way to mark the containers as belonging to the same network would be useful.

An example design follows:

Allow the defining of a `dockerNetwork` property on the `ServiceDescription` object. Container services that share the same network name are implicitly joined together into that network.

```yaml
- name: elasticsearch
  dockerImage: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
  env:
    'discovery.type': 'single-node'
  dockerNetwork: elknet
  bindings:
    - port: 9300
    - port: 9200

- name: kibana
  dockerImage: docker.elastic.co/kibana/kibana:7.5.1
  dockerNetwork: elknet
  bindings:    
    - port: 5601
```

m8s could auto define a random network with a random name like 'elknet_a175ce22-4' and then add both containers to it. I would also recommend automatically adding the service name as an alias or perhaps allowing it to be an additional config option

Example commands below:
```docker
docker network create elknet_a175ce22-4
docker network connect --alias elasticsearch elknet_a175ce22-4 elasticsearch_b613c144-b
docker network connect --alias kibana elknet_a175ce22-4 kibana_17185168-a
```
