### ISSUE TITLE
Add port mapping for Docker containers

### ISSUE THREAD

**Issue by nj0yeh** [davidfowl/Micronetes#45]
Please add the possibility to specify an internal and an external port for Docker containers. We run multiple MySQL Docker containers (that all listen to port 3306) and want to expose them to different external ports.

You can achieve this by replacing the second port in `$"-p {p.Port}:{p.Port}"` with the internal port.

**Comment by davidfowl** [comment]
Yep, this makes sense.

**Comment by davidfowl** [comment]
This looks a bit verbose:

```yaml
- name: web
  dockerImage: davidfowl/web
  bindings: 
    - port: 5000
- name: api
  dockerImage: davidfowl/api
  replicas: 2
  bindings: 
    - port: 5001
      internalPort: 80
```

I could support the docker style syntax.

```yaml
- name: web
  dockerImage: davidfowl/web
  bindings: 
    - port: 5000
- name: api
  dockerImage: davidfowl/api
  replicas: 2
  bindings: 
    - port: "5001:80"
```
